### ISSUE TITLE
yolov3-spp-matrix.cfg in ultralytics/yolov3 - missing 'share_index' field implementation

### ISSUE THREAD

**Issue by glenn-jocher** [WongKinYiu/CrossStagePartialNetworks#2]
Hi @WongKinYiu thanks for the great work here! I introduced new error-checking in https://github.com/ultralytics/yolov3 for custom cfgs, and after running your yolov3-spp-matrix.cfg through, I just realized my implementation is not handling your 'share_index' field correctly. What do I do exactly with the value `share_index=115` here?
```python
AssertionError: Unsupported field 'share_index' in cfg/yolov3-spp-matrix.cfg. 
```

https://github.com/WongKinYiu/CrossStagePartialNetworks/blob/ff762e58750a2261d64855ac9c3a3ea1a993a24a/in%20progress/yolov3-spp-matrix.cfg#L926-L933

**Comment by WongKinYiu** [comment]
@glenn-jocher 

In https://github.com/AlexeyAB/darknet/issues/3772#issuecomment-527089088, @AlexeyAB implement the weight sharing for different layers.

However, because the filter number is different for `share_index=` in https://github.com/WongKinYiu/CrossStagePartialNetworks/blob/ff762e58750a2261d64855ac9c3a3ea1a993a24a/in%20progress/yolov3-spp-matrix.cfg#L926-L933.
So just comment the lines which starts with `share_index=`  →  `#share_index=`.
The weight sharing for partial of filters is in progress now.

**Comment by glenn-jocher** [comment]
@WongKinYiu ok got it. Then it should produce the same results I saw before, since I was ignoring this share_index field.
